import { useEffect, useMemo, useState } from 'react'
import { ArchiveRestore, CheckCircle2, ChevronRight, CirclePlus, Package, Printer, RotateCcw, Search, Trash2, Truck, Warehouse as WarehouseIcon } from 'lucide-react'
import type { AppState, MovementType, Order, OrderStatus, ProductKey } from './types'
import { demoState, makeOrderNumber } from './lib/data'
import { activeStatuses, allPacked, available, breakdown, deductOrderStock, deductStatuses, normalize, productName, reserved } from './lib/logic'
import { loadState, saveState } from './lib/storage'
import { BottomNav, SideNav } from './components/Nav'
import { Card, Empty, Field, Modal, PageHeader } from './components/UI'
import './index.css'

const statuses:OrderStatus[]=['Нова','Во подготовка','Спакувана','Излезена','Испратена','Доставена','Откажана']
const statusClass=(s:OrderStatus)=>`status ${s.replaceAll(' ','-').toLowerCase()}`

function App(){
 const [state,setState]=useState<AppState>(loadState)
 const [page,setPage]=useState('dashboard')
 const [selected,setSelected]=useState<string|null>(null)
 const [showOrder,setShowOrder]=useState(false)
 const [showEntry,setShowEntry]=useState(false)
 const [query,setQuery]=useState('')
 useEffect(()=>saveState(state),[state])
 const selectedOrder=state.orders.find(o=>o.id===selected)||null
 const r=useMemo(()=>reserved(state),[state]); const a=useMemo(()=>available(state),[state])
 const patchOrder=(id:string,patch:Partial<Order>)=>setState(s=>({...s,orders:s.orders.map(o=>o.id===id?{...o,...patch}:o)}))
 const changeStatus=(o:Order,next:OrderStatus)=>{
  if(next==='Спакувана'&&!allPacked(o)){alert('Прво означи ги сите ставки како спакувани.');return}
  if(deductStatuses.has(next)&&!o.stockDeducted){const updated=deductOrderStock(state,o,next);if(!updated){alert('Нема доволно залиха за оваа нарачка.');return}setState(updated);return}
  patchOrder(o.id,{status:next})
 }
 const printOrder=(o:Order)=>{setSelected(o.id);setTimeout(()=>window.print(),50)}
 return <div className="app"><SideNav page={page} setPage={setPage}/><main className="main">
  {page==='dashboard'&&<Dashboard state={state} r={r} a={a} setPage={setPage} openOrder={id=>{setSelected(id);setPage('packing')}}/>}
  {page==='orders'&&<Orders state={state} query={query} setQuery={setQuery} onOpen={id=>{setSelected(id);setPage('packing')}} onNew={()=>setShowOrder(true)} onDelete={id=>{if(confirm('Да се избрише нарачката?'))setState(s=>({...s,orders:s.orders.filter(o=>o.id!==id)}))}}/>}
  {page==='packing'&&<Packing order={selectedOrder||state.orders[0]||null} onSelect={setSelected} orders={state.orders} patch={patchOrder} changeStatus={changeStatus} printOrder={printOrder}/>} 
  {page==='warehouse'&&<WarehousePage state={state} onEntry={()=>setShowEntry(true)}/>} 
  {page==='clients'&&<ClientsPage state={state}/>} 
  {page==='movements'&&<MovementsPage state={state}/>} 
  {page==='printing'&&<PrintingPage state={state} printOrder={printOrder}/>} 
  {page==='settings'&&<SettingsPage onReset={()=>{if(confirm('Да се вратат демо податоците? Сите тековни податоци ќе се избришат.')){setState(demoState());setSelected(null)}}}/>} 
 </main><BottomNav page={page} setPage={setPage}/>
 {showOrder&&<NewOrder state={state} onClose={()=>setShowOrder(false)} onSave={o=>{setState(s=>({...s,orders:[o,...s.orders],clients:s.clients.some(c=>c.name.toLowerCase()===o.client.toLowerCase())?s.clients:[...s.clients,{id:crypto.randomUUID(),name:o.client,city:o.city,phone:'',contactPerson:'',address:''}]}));setShowOrder(false)}}/>}
 {showEntry&&<StockEntry onClose={()=>setShowEntry(false)} onSave={(p,t,pack,pieces,party,note,date)=>{setState(s=>{const delta=(t==='Излез'||t==='Оштетување')?-1:1;const total=p==='p025'?pack*15+pieces:p==='p15'?pack*6+pieces:pieces;const current=p==='p025'?s.warehouse.p025.total:p==='p15'?s.warehouse.p15.total:s.warehouse.flyers;if(current+delta*total<0){alert('Не е дозволена негативна залиха.');return s}return {...s,warehouse:p==='p025'?{...s.warehouse,p025:normalize(current+delta*total,15)}:p==='p15'?{...s.warehouse,p15:normalize(current+delta*total,6)}:{...s.warehouse,flyers:current+delta*total},movements:[{id:crypto.randomUUID(),date,product:p,type:t,packages:pack,pieces,party,orderNumber:'',note},...s.movements]}});setShowEntry(false)}}/>}
 <div className="print-only">{selectedOrder&&<PackingPrint o={selectedOrder}/>}</div>
 </div>
}

function Dashboard({state,r,a,setPage,openOrder}:{state:AppState;r:any;a:any;setPage:(p:string)=>void;openOrder:(id:string)=>void}){const packed=state.orders.filter(o=>o.status==='Спакувана').length,sent=state.orders.filter(o=>['Излезена','Испратена','Доставена'].includes(o.status)).length;return <><PageHeader title="Контролна табла" action={<button className="primary" onClick={()=>setPage('orders')}><CirclePlus size={18}/> Нова нарачка</button>}/><div className="hero"><div><span>Магацин во реално време</span><h2>Залиха, пакување и испораки на едно место.</h2></div><div className="pulse"><i/> Системот е активен</div></div><div className="stock-grid"><StockCard title="0.25 L" packs={state.warehouse.p025.packages} pieces={state.warehouse.p025.pieces} total={state.warehouse.p025.total} reserved={r.p025} available={a.p025} onClick={()=>setPage('warehouse')}/><StockCard title="1.5 L BIB" packs={state.warehouse.p15.packages} pieces={state.warehouse.p15.pieces} total={state.warehouse.p15.total} reserved={r.p15} available={a.p15} onClick={()=>setPage('warehouse')}/><StockCard title="Флаери" packs={0} pieces={state.warehouse.flyers} total={state.warehouse.flyers} reserved={r.flyers} available={a.flyers} onClick={()=>setPage('warehouse')}/></div><div className="metric-grid"><Metric label="Активни нарачки" value={state.orders.filter(o=>activeStatuses.has(o.status)).length} onClick={()=>setPage('orders')}/><Metric label="Спакувани" value={packed} onClick={()=>setPage('packing')}/><Metric label="Испратени/излезени" value={sent} onClick={()=>setPage('movements')}/><Metric label="Клиенти" value={state.clients.length} onClick={()=>setPage('clients')}/></div><Card><div className="section-title"><div><h3>Следни за пакување</h3><p>Најнови активни нарачки</p></div><button className="ghost" onClick={()=>setPage('packing')}>Отвори пакување <ChevronRight size={16}/></button></div><div className="compact-list">{state.orders.filter(o=>activeStatuses.has(o.status)).slice(0,5).map(o=><button type="button" key={o.id} onClick={()=>openOrder(o.id)}><span><strong>{o.client}</strong><small>{o.city} • {o.number}</small></span><span className={statusClass(o.status)}>{o.status}</span></button>)}</div></Card></>}
const StockCard=({title,packs,pieces,total,reserved,available,onClick}:{title:string;packs:number;pieces:number;total:number;reserved:number;available:number;onClick?:()=>void})=>onClick?<button type="button" className="card stock-card dashboard-link" onClick={onClick}><div className="stock-icon"><Package/></div><div className="stock-top"><h3>{title}</h3><strong>{total}</strong></div><div className="stock-split"><span><b>{packs}</b> пакети</span><span><b>{pieces}</b> парчиња</span></div><div className="bar"><i style={{width:`${Math.min(100,total?reserved/total*100:0)}%`}}/></div><div className="stock-foot"><span>Резервирано: <b>{reserved}</b></span><span>Слободно: <b>{available}</b></span></div></button>:<Card className="stock-card"><div className="stock-icon"><Package/></div><div className="stock-top"><h3>{title}</h3><strong>{total}</strong></div><div className="stock-split"><span><b>{packs}</b> пакети</span><span><b>{pieces}</b> парчиња</span></div><div className="bar"><i style={{width:`${Math.min(100,total?reserved/total*100:0)}%`}}/></div><div className="stock-foot"><span>Резервирано: <b>{reserved}</b></span><span>Слободно: <b>{available}</b></span></div></Card>
const Metric=({label,value,onClick}:{label:string;value:number;onClick?:()=>void})=>onClick?<button type="button" className="card metric dashboard-link" onClick={onClick}><span>{label}</span><strong>{value}</strong></button>:<Card className="metric"><span>{label}</span><strong>{value}</strong></Card>

function Orders({state,query,setQuery,onOpen,onNew,onDelete}:{state:AppState;query:string;setQuery:(v:string)=>void;onOpen:(id:string)=>void;onNew:()=>void;onDelete:(id:string)=>void}){const list=state.orders.filter(o=>(o.client+' '+o.city+' '+o.number).toLowerCase().includes(query.toLowerCase()));return <><PageHeader title="Нарачки" action={<button className="primary" onClick={onNew}><CirclePlus size={18}/> Нова нарачка</button>}/><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Пребарај клиент, град или број..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><Card>{list.length===0?<Empty text="Нема пронајдени нарачки."/>:<div className="orders-list">{list.map(o=><article key={o.id} onClick={()=>onOpen(o.id)}><div className="order-main"><div className="order-number">{o.number}</div><h3>{o.client}</h3><p>{o.city} • {o.date}</p></div><div className="order-qty"><span>0.25 L <b>{o.qty025+o.free025} пак.</b>{(o.qty025Pieces||0)+(o.free025Pieces||0)>0&&` + ${(o.qty025Pieces||0)+(o.free025Pieces||0)} пар.`}</span><span>BIB <b>{o.qty15} пак.</b>{(o.qty15Pieces||0)>0&&` + ${o.qty15Pieces} пар.`}</span><span>Флаери <b>{o.flyers} пар.</b></span></div><div className="order-actions"><span className={statusClass(o.status)}>{o.status}</span><button className="icon-btn danger" onClick={e=>{e.stopPropagation();onDelete(o.id)}}><Trash2 size={17}/></button><ChevronRight size={20}/></div></article>)}</div>}</Card></>}

function Packing({order,orders,onSelect,patch,changeStatus,printOrder}:{order:Order|null;orders:Order[];onSelect:(id:string)=>void;patch:(id:string,p:Partial<Order>)=>void;changeStatus:(o:Order,s:OrderStatus)=>void;printOrder:(o:Order)=>void}){if(!order)return <><PageHeader title="Пакување"/><Empty text="Нема нарачки за пакување."/></>;const total025Packages=order.qty025+order.free025,total025Pieces=(order.qty025Pieces||0)+(order.free025Pieces||0);return <><PageHeader title="Пакување" action={<button className="ghost" onClick={()=>printOrder(order)}><Printer size={18}/> Печати нарачка</button>}/><div className="packing-layout"><Card className="order-selector"><h3>Нарачки</h3>{orders.map(o=><button className={o.id===order.id?'selected':''} onClick={()=>onSelect(o.id)} key={o.id}><div><b>{o.client}</b><small>{o.number}</small></div><span className={statusClass(o.status)}>{o.status}</span></button>)}</Card><div className="packing-main"><Card className="packing-summary"><div><span>{order.number}</span><h2>{order.client}</h2><p>{order.city} • {order.date}</p></div><select value={order.status} onChange={e=>changeStatus(order,e.target.value as OrderStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Card><div className="pack-rows"><PackRow checked={order.packed.regular025} onChange={v=>patch(order.id,{packed:{...order.packed,regular025:v}})} title="0.25 L" qty={order.qty025} detail={breakdown(order.qty025,order.qty025Pieces||0)}/><PackRow checked={order.packed.bib15} onChange={v=>patch(order.id,{packed:{...order.packed,bib15:v}})} title="1.5 L BIB" qty={order.qty15} detail={breakdown(order.qty15,order.qty15Pieces||0)}/><PackRow checked={order.packed.free025} onChange={v=>patch(order.id,{packed:{...order.packed,free025:v}})} title="Гратис 0.25 L" qty={order.free025} detail={`${breakdown(order.free025,order.free025Pieces||0)} • одделно`}/><PackRow checked={order.packed.flyers} onChange={v=>patch(order.id,{packed:{...order.packed,flyers:v}})} title="Флаери" qty={order.flyers} detail={`${order.flyers} парчиња`}/></div><Card className="take-card"><div><WarehouseIcon/><span>Вкупно за земање од магацин</span></div><h3>{total025Packages} пакети{total025Pieces>0?` + ${total025Pieces} парчиња`:''} 0.25 L</h3><p>редовни {order.qty025} пак. + гратис {order.free025} пак.{total025Pieces>0?` • дополнителни ${total025Pieces} пар.`:''}</p></Card></div></div></>}
const PackRow=({checked,onChange,title,qty,detail}:{checked:boolean;onChange:(v:boolean)=>void;title:string;qty:number;detail:string})=><label className={`pack-row ${checked?'done':''}`}><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><div className="check-ui">{checked&&<CheckCircle2/>}</div><div><h3>{title}</h3><p>{detail}</p></div><strong>{qty}</strong></label>

function WarehousePage({state,onEntry}:{state:AppState;onEntry:()=>void}){return <><PageHeader title="Магацин" action={<button className="primary" onClick={onEntry}><CirclePlus size={18}/> Ново движење</button>}/><div className="stock-grid"><StockCard title="0.25 L" packs={state.warehouse.p025.packages} pieces={state.warehouse.p025.pieces} total={state.warehouse.p025.total} reserved={reserved(state).p025} available={available(state).p025}/><StockCard title="1.5 L BIB" packs={state.warehouse.p15.packages} pieces={state.warehouse.p15.pieces} total={state.warehouse.p15.total} reserved={reserved(state).p15} available={available(state).p15}/><StockCard title="Флаери" packs={0} pieces={state.warehouse.flyers} total={state.warehouse.flyers} reserved={reserved(state).flyers} available={available(state).flyers}/></div><Card><div className="section-title"><div><h3>Последни движења</h3><p>Влезови, излези и корекции</p></div></div><MovementTable movements={state.movements.slice(0,8)}/></Card></>}
function ClientsPage({state}:{state:AppState}){return <><PageHeader title="Клиенти"/><div className="client-grid">{state.clients.map(c=>{const orders=state.orders.filter(o=>o.client===c.name);return <Card key={c.id} className="client-card"><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><h3>{c.name}</h3><p>{c.city}</p><div><span>Нарачки <b>{orders.length}</b></span><span>Последна <b>{orders[0]?.date||'—'}</b></span></div><small>{c.phone||'Нема внесен телефон'} • {c.contactPerson||'Нема контакт лице'}</small></Card>})}</div></>}
function MovementsPage({state}:{state:AppState}){return <><PageHeader title="Историја на залиха"/><Card><MovementTable movements={state.movements}/></Card></>}
const MovementTable=({movements}:{movements:AppState['movements']})=>movements.length===0?<Empty text="Сè уште нема движења на залиха."/>:<div className="table-wrap"><table><thead><tr><th>Датум</th><th>Производ</th><th>Тип</th><th>Пакети</th><th>Парчиња</th><th>Клиент / добавувач</th><th>Нарачка</th><th>Забелешка</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{m.date}</td><td>{productName(m.product)}</td><td><span className="status">{m.type}</span></td><td>{m.packages}</td><td>{m.pieces}</td><td>{m.party||'—'}</td><td>{m.orderNumber||'—'}</td><td>{m.note||'—'}</td></tr>)}</tbody></table></div>
function PrintingPage({state,printOrder}:{state:AppState;printOrder:(o:Order)=>void}){const active=state.orders.filter(o=>activeStatuses.has(o.status));const printGroup=()=>{const html=`<html><head><title>MAGACIN PRO</title><style>body{font-family:Arial;padding:24px}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #aaa;padding:8px;text-align:left}</style></head><body><h1>MAGACIN PRO</h1><h2>Активни нарачки</h2><table><tr><th>Број</th><th>Клиент</th><th>Град</th><th>0.25 L</th><th>BIB</th><th>Гратис</th><th>Флаери</th><th>Статус</th></tr>${active.map(o=>`<tr><td>${o.number}</td><td>${o.client}</td><td>${o.city}</td><td>${breakdown(o.qty025,o.qty025Pieces||0)}</td><td>${breakdown(o.qty15,o.qty15Pieces||0)}</td><td>${breakdown(o.free025,o.free025Pieces||0)}</td><td>${o.flyers} пар.</td><td>${o.status}</td></tr>`).join('')}</table><script>window.print()</script></body></html>`;const w=window.open('','_blank');w?.document.write(html);w?.document.close()};return <><PageHeader title="Печатење" action={<button className="primary" onClick={printGroup}><Printer size={18}/> Печати активни нарачки</button>}/><Card><div className="orders-list">{state.orders.map(o=><article key={o.id}><div className="order-main"><div className="order-number">{o.number}</div><h3>{o.client}</h3><p>{o.city} • {o.date}</p></div><button className="ghost" onClick={()=>printOrder(o)}><Printer size={17}/> Печати нарачка</button></article>)}</div></Card></>}
function SettingsPage({onReset}:{onReset:()=>void}){return <><PageHeader title="Поставки"/><Card className="settings-card"><ArchiveRestore/><div><h3>Демо податоци</h3><p>Врати ја почетната залиха, клиентите и осумте демо нарачки.</p></div><button className="danger-btn" onClick={onReset}><RotateCcw size={18}/> Ресетирај демо податоци</button></Card><Card className="settings-card"><Truck/><div><h3>Подготвено за идно проширување</h3><p>Структурата е одвоена за подоцнежно поврзување со Supabase, логирање, повеќе корисници, OCR, QR/баркод и возачки режим.</p></div></Card></>}

function NewOrder({state,onClose,onSave}:{state:AppState;onClose:()=>void;onSave:(o:Order)=>void}){const [f,setF]=useState({client:'',city:'',p025:'0',e025:'0',p15:'0',e15:'0',free:'0',freePieces:'0',flyers:'0',note:''});return <Modal title="Нова нарачка" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({id:crypto.randomUUID(),number:makeOrderNumber(state.orders),client:f.client,city:f.city,date:new Date().toISOString().slice(0,10),qty025:+f.p025,qty025Pieces:+f.e025,qty15:+f.p15,qty15Pieces:+f.e15,free025:+f.free,free025Pieces:+f.freePieces,flyers:+f.flyers,note:f.note,status:'Нова',packed:{regular025:false,bib15:false,free025:false,flyers:false},stockDeducted:false})}} className="form-grid"><Field label="Пакети 0.25 L"><input min="0" type="number" value={f.p025} onChange={e=>setF({...f,p025:e.target.value})}/></Field><Field label="Дополнителни парчиња 0.25 L"><input min="0" max="14" type="number" value={f.e025} onChange={e=>setF({...f,e025:e.target.value})}/></Field><Field label="Пакети 1.5 L BIB"><input min="0" type="number" value={f.p15} onChange={e=>setF({...f,p15:e.target.value})}/></Field><Field label="Дополнителни парчиња BIB"><input min="0" max="5" type="number" value={f.e15} onChange={e=>setF({...f,e15:e.target.value})}/></Field><Field label="Гратис пакети 0.25 L"><input min="0" type="number" value={f.free} onChange={e=>setF({...f,free:e.target.value})}/></Field><Field label="Гратис дополнителни парчиња"><input min="0" max="14" type="number" value={f.freePieces} onChange={e=>setF({...f,freePieces:e.target.value})}/></Field><Field label="Флаери (парчиња)"><input min="0" type="number" value={f.flyers} onChange={e=>setF({...f,flyers:e.target.value})}/></Field><div className="calc-banner">0.25 L: <b>{f.p025}</b> пак. + <b>{f.e025}</b> пар. • BIB: <b>{f.p15}</b> пак. + <b>{f.e15}</b> пар. • Гратис: <b>{f.free}</b> пак. + <b>{f.freePieces}</b> пар.</div><Field label="Клиент"><input required value={f.client} onChange={e=>setF({...f,client:e.target.value})}/></Field><Field label="Град"><input required value={f.city} onChange={e=>setF({...f,city:e.target.value})}/></Field><Field label="Забелешка"><textarea value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></Field><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Откажи</button><button className="primary">Зачувај нарачка</button></div></form></Modal>}
function StockEntry({onClose,onSave}:{onClose:()=>void;onSave:(p:ProductKey,t:MovementType,pack:number,pieces:number,party:string,note:string,date:string)=>void}){const [f,setF]=useState({product:'p025' as ProductKey,type:'Влез' as MovementType,packages:'0',pieces:'0',party:'',note:'',doc:'',date:new Date().toISOString().slice(0,10)});return <Modal title="Ново движење на залиха" onClose={onClose}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave(f.product,f.type,+f.packages,+f.pieces,f.party,`${f.doc?`Документ: ${f.doc}. `:''}${f.note}`,f.date)}}><Field label="Производ"><select value={f.product} onChange={e=>setF({...f,product:e.target.value as ProductKey})}><option value="p025">0.25 L</option><option value="p15">1.5 L BIB</option><option value="flyers">Флаери</option></select></Field><Field label="Тип"><select value={f.type} onChange={e=>setF({...f,type:e.target.value as MovementType})}>{['Влез','Излез','Корекција','Враќање','Оштетување'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Пакети"><input type="number" min="0" value={f.packages} disabled={f.product==='flyers'} onChange={e=>setF({...f,packages:e.target.value})}/></Field><Field label="Индивидуални парчиња"><input type="number" min="0" value={f.pieces} onChange={e=>setF({...f,pieces:e.target.value})}/></Field><Field label="Добавувач / клиент"><input value={f.party} onChange={e=>setF({...f,party:e.target.value})}/></Field><Field label="Документ / фактура"><input value={f.doc} onChange={e=>setF({...f,doc:e.target.value})}/></Field><Field label="Датум"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Забелешка"><textarea value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></Field><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Откажи</button><button className="primary">Зачувај движење</button></div></form></Modal>}
function PackingPrint({o}:{o:Order}){return <div className="print-sheet"><h1>MAGACIN PRO</h1><div className="print-meta"><b>{o.number}</b><span>{o.date}</span><span>{o.client}</span><span>{o.city}</span></div><table><thead><tr><th>Производ</th><th>Нарачано</th><th>Спакувано</th><th>Проверка</th><th>Пакување</th></tr></thead><tbody><tr><td>0.25 L</td><td>{o.qty025} пак.</td><td>_____</td><td>☐</td><td>{breakdown(o.qty025,o.qty025Pieces||0)}</td></tr><tr><td>1.5 L BIB</td><td>{o.qty15} пак.</td><td>_____</td><td>☐</td><td>{breakdown(o.qty15,o.qty15Pieces||0)}</td></tr><tr><td>Гратис 0.25 L</td><td>{o.free025} пак.</td><td>_____</td><td>☐</td><td>{breakdown(o.free025,o.free025Pieces||0)} • одделно</td></tr><tr><td>Флаери</td><td>{o.flyers} пар.</td><td>_____</td><td>☐</td><td>Парчиња</td></tr></tbody></table><p><b>Забелешка:</b> {o.note||'____________________________________________'}</p><div className="sign"><span>Спакувал: __________________</span><span>Проверил: __________________</span></div></div>}
export default App
