import { useMemo, useState, type FormEvent } from 'react'
import { ArchiveRestore, CheckCircle2, ChevronRight, CirclePlus, Cloud, CloudOff, LogIn, LogOut, Package, Printer, RotateCcw, Search, ShieldCheck, Trash2, Truck, Warehouse as WarehouseIcon } from 'lucide-react'
import type { AppState, MovementType, Order, OrderStatus, ProductKey } from './types'
import { demoState, makeOrderNumber } from './lib/data'
import { activeStatuses, allPacked, available, breakdown, deductOrderStock, deductStatuses, normalize, productName, reserved, updatePackedItem } from './lib/logic'
import { supabase, syncEnabled } from './lib/supabase'
import { useSyncedState, type SyncStatus } from './lib/useSyncedState'
import { appVersion } from './pwa'
import { BottomNav, SideNav } from './components/Nav'
import { Card, Empty, Field, Modal, PageHeader } from './components/UI'
import { AdminPage } from './components/AdminPage'
import './index.css'

const statuses:OrderStatus[]=['Нова','Во подготовка','Спакувана','Излезена','Испратена','Доставена','Откажана']
const statusClass=(s:OrderStatus)=>`status ${s.replaceAll(' ','-').toLowerCase()}`
const localDemo=import.meta.env.DEV&&new URLSearchParams(window.location.search).has('local-demo')
const localMode=!syncEnabled||localDemo

function App(){
 const {state,setState,session,profile,authReady,syncStatus,syncError,recordAudit}=useSyncedState()
 const [page,setPage]=useState('dashboard')
 const [selected,setSelected]=useState<string|null>(null)
 const [showOrder,setShowOrder]=useState(false)
 const [showEntry,setShowEntry]=useState(false)
 const [query,setQuery]=useState('')
 const selectedOrder=state.orders.find(o=>o.id===selected)||null
 const r=useMemo(()=>reserved(state),[state]); const a=useMemo(()=>available(state),[state])
 const isAdmin=profile?.role==='admin'
 if(!authReady&&!localMode)return <div className="auth-shell"><div className="auth-card"><div className="auth-logo">MP</div><h1>MAGACIN PRO</h1><p>Се поврзува со заедничката база...</p></div></div>
 if(!session&&!localMode)return <AuthScreen/>
 const patchPacked=(o:Order,key:keyof Order['packed'],value:boolean)=>{
  const updated=updatePackedItem(state,o.id,key,value)
  if(!updated){alert('Нема доволно залиха за оваа нарачка.');return}
  setState(updated)
  void recordAudit('order.packing_checked','order',o.id,{number:o.number,item:key,checked:value,auto_packed:updated.orders.find(order=>order.id===o.id)?.status==='Спакувана'&&o.status!=='Спакувана'})
 }
 const changeStatus=(o:Order,next:OrderStatus)=>{
  if(next==='Спакувана'&&!allPacked(o)){alert('Прво означи ги сите ставки како спакувани.');return}
  if(deductStatuses.has(next)&&!o.stockDeducted){const updated=deductOrderStock(state,o,next);if(!updated){alert('Нема доволно залиха за оваа нарачка.');return}setState(updated);void recordAudit('order.status_changed','order',o.id,{number:o.number,from:o.status,to:next});return}
  void recordAudit('order.status_changed','order',o.id,{number:o.number,from:o.status,to:next})
  setState(s=>({...s,orders:s.orders.map(order=>order.id===o.id?{...order,status:next}:order)}))
 }
 const deleteOrder=(id:string)=>{const order=state.orders.find(item=>item.id===id);if(!order||!confirm('Да се избрише нарачката?'))return;setState(s=>({...s,orders:s.orders.filter(item=>item.id!==id)}));void recordAudit('order.deleted','order',id,{number:order.number,client:order.client})}
 const saveNewOrder=(o:Order)=>{setState(s=>({...s,orders:[o,...s.orders],clients:s.clients.some(c=>c.name.toLowerCase()===o.client.toLowerCase())?s.clients:[...s.clients,{id:crypto.randomUUID(),name:o.client,city:o.city,phone:'',contactPerson:'',address:''}]}));void recordAudit('order.created','order',o.id,{number:o.number,client:o.client,city:o.city});setShowOrder(false)}
 const saveStockEntry=(p:ProductKey,t:MovementType,pack:number,pieces:number,party:string,note:string,date:string)=>{const delta=(t==='Излез'||t==='Оштетување')?-1:1;const total=p==='p025'?pack*15+pieces:p==='p15'?pack*6+pieces:pieces;const current=p==='p025'?state.warehouse.p025.total:p==='p15'?state.warehouse.p15.total:state.warehouse.flyers;if(current+delta*total<0){alert('Не е дозволена негативна залиха.');return}setState(s=>({...s,warehouse:p==='p025'?{...s.warehouse,p025:normalize(s.warehouse.p025.total+delta*total,15)}:p==='p15'?{...s.warehouse,p15:normalize(s.warehouse.p15.total+delta*total,6)}:{...s.warehouse,flyers:s.warehouse.flyers+delta*total},movements:[{id:crypto.randomUUID(),date,product:p,type:t,packages:pack,pieces,party,orderNumber:'',note},...s.movements]}));void recordAudit('stock.movement','stock',p,{type:t,packages:pack,pieces,party});setShowEntry(false)}
 const printOrder=(o:Order)=>{setSelected(o.id);setTimeout(()=>window.print(),50)}
 return <div className="app"><SideNav page={page} setPage={setPage} isAdmin={isAdmin}/><main className="main">
  {page==='dashboard'&&<Dashboard state={state} r={r} a={a} setPage={setPage} openOrder={id=>{setSelected(id);setPage('packing')}} openPacked={()=>{setSelected(state.orders.find(o=>o.status==='Спакувана')?.id||null);setPage('packing')}}/>}
  {page==='orders'&&<Orders state={state} query={query} setQuery={setQuery} onOpen={id=>{setSelected(id);setPage('packing')}} onNew={()=>setShowOrder(true)} onDelete={isAdmin?deleteOrder:undefined}/>}
  {page==='packing'&&<Packing order={selectedOrder||state.orders[0]||null} onSelect={setSelected} orders={state.orders} patchPacked={patchPacked} changeStatus={changeStatus} printOrder={printOrder}/>}
  {page==='warehouse'&&<WarehousePage state={state} onEntry={()=>setShowEntry(true)}/>} 
  {page==='clients'&&<ClientsPage state={state}/>} 
  {page==='movements'&&<MovementsPage state={state}/>} 
  {page==='printing'&&<PrintingPage state={state} printOrder={printOrder}/>} 
  {page==='admin'&&isAdmin&&session&&<AdminPage currentUserId={session.user.id}/>}
  {page==='settings'&&<SettingsPage
   syncStatus={syncStatus}
   syncError={syncError}
   email={session?.user.email||'Локален тест'}
   role={profile?.role||'operator'}
   isAdmin={isAdmin}
   openAdmin={()=>setPage('admin')}
   onReset={isAdmin?()=>{if(confirm('Да се вратат демо податоците? Сите тековни податоци ќе се избришат.')){setState(demoState());setSelected(null);void recordAudit('app.demo_reset','app',null,{})}}:undefined}
  />}
 </main><BottomNav page={page} setPage={setPage}/>
 {showOrder&&<NewOrder state={state} onClose={()=>setShowOrder(false)} onSave={saveNewOrder}/>}
 {showEntry&&<StockEntry onClose={()=>setShowEntry(false)} onSave={saveStockEntry}/>}
 <div className="print-only">{selectedOrder&&<PackingPrint o={selectedOrder}/>}</div>
 </div>
}

function AuthScreen(){
 const [fullName,setFullName]=useState('')
 const [email,setEmail]=useState('')
 const [password,setPassword]=useState('')
 const [mode,setMode]=useState<'login'|'signup'>('login')
 const [busy,setBusy]=useState(false)
 const [message,setMessage]=useState('')
 const submit=async(e:FormEvent)=>{
  e.preventDefault();setBusy(true);setMessage('')
  const result=mode==='login'
   ?await supabase.auth.signInWithPassword({email,password})
   :await supabase.auth.signUp({email,password,options:{data:{full_name:fullName.trim()}}})
  setBusy(false)
  if(result.error){setMessage(result.error.message);return}
  if(mode==='signup'&&!result.data.session)setMessage('Провери ја е-поштата и потврди ја регистрацијата, па најави се.')
 }
 return <div className="auth-shell"><form className="auth-card" onSubmit={submit}><div className="auth-logo">MP</div><span>MAGACIN PRO</span><h1>{mode==='login'?'Најава':'Нов профил'}</h1><p>Секој вработен користи свој профил, а сите работат во истиот заеднички магацин.</p>{mode==='signup'&&<label>Име и презиме<input required autoComplete="name" value={fullName} onChange={e=>setFullName(e.target.value)}/></label>}<label>Е-пошта<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Лозинка<input type="password" required minLength={6} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<div className="auth-message">{message}</div>}<button className="primary auth-submit" disabled={busy}><LogIn size={18}/>{busy?'Почекај...':mode==='login'?'Најави се':'Регистрирај се'}</button><button type="button" className="auth-switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'Немаш профил? Регистрирај се':'Имаш профил? Најави се'}</button></form></div>
}

function Dashboard({state,r,a,setPage,openOrder,openPacked}:{state:AppState;r:any;a:any;setPage:(p:string)=>void;openOrder:(id:string)=>void;openPacked:()=>void}){const packed=state.orders.filter(o=>o.status==='Спакувана').length,sent=state.orders.filter(o=>['Излезена','Испратена','Доставена'].includes(o.status)).length;return <><PageHeader title="Контролна табла" action={<button className="primary" onClick={()=>setPage('orders')}><CirclePlus size={18}/> Нова нарачка</button>}/><div className="hero"><div><span>Магацин во реално време</span><h2>Залиха, пакување и испораки на едно место.</h2></div><div className="pulse"><i/> Системот е активен</div></div><div className="stock-grid"><StockCard title="0.25 L" packs={state.warehouse.p025.packages} pieces={state.warehouse.p025.pieces} total={state.warehouse.p025.total} reserved={r.p025} available={a.p025} onClick={()=>setPage('warehouse')}/><StockCard title="1.5 L BIB" packs={state.warehouse.p15.packages} pieces={state.warehouse.p15.pieces} total={state.warehouse.p15.total} reserved={r.p15} available={a.p15} onClick={()=>setPage('warehouse')}/><StockCard title="Флаери" packs={0} pieces={state.warehouse.flyers} total={state.warehouse.flyers} reserved={r.flyers} available={a.flyers} onClick={()=>setPage('warehouse')}/></div><div className="metric-grid"><Metric label="Активни нарачки" value={state.orders.filter(o=>activeStatuses.has(o.status)).length} onClick={()=>setPage('orders')}/><Metric label="Спакувани" value={packed} onClick={openPacked}/><Metric label="Испратени/излезени" value={sent} onClick={()=>setPage('movements')}/><Metric label="Клиенти" value={state.clients.length} onClick={()=>setPage('clients')}/></div><Card><div className="section-title"><div><h3>Следни за пакување</h3><p>Најнови активни нарачки</p></div><button className="ghost" onClick={()=>setPage('packing')}>Отвори пакување <ChevronRight size={16}/></button></div><div className="compact-list">{state.orders.filter(o=>activeStatuses.has(o.status)).slice(0,5).map(o=><button type="button" key={o.id} onClick={()=>openOrder(o.id)}><span><strong>{o.client}</strong><small>{o.city} • {o.number}</small></span><span className={statusClass(o.status)}>{o.status}</span></button>)}</div></Card></>}
const StockCard=({title,packs,pieces,total,reserved,available,onClick}:{title:string;packs:number;pieces:number;total:number;reserved:number;available:number;onClick?:()=>void})=>onClick?<button type="button" className="card stock-card dashboard-link" onClick={onClick}><div className="stock-icon"><Package/></div><div className="stock-top"><h3>{title}</h3><strong>{total}</strong></div><div className="stock-split"><span><b>{packs}</b> пакети</span><span><b>{pieces}</b> парчиња</span></div><div className="bar"><i style={{width:`${Math.min(100,total?reserved/total*100:0)}%`}}/></div><div className="stock-foot"><span>Резервирано: <b>{reserved}</b></span><span>Слободно: <b>{available}</b></span></div></button>:<Card className="stock-card"><div className="stock-icon"><Package/></div><div className="stock-top"><h3>{title}</h3><strong>{total}</strong></div><div className="stock-split"><span><b>{packs}</b> пакети</span><span><b>{pieces}</b> парчиња</span></div><div className="bar"><i style={{width:`${Math.min(100,total?reserved/total*100:0)}%`}}/></div><div className="stock-foot"><span>Резервирано: <b>{reserved}</b></span><span>Слободно: <b>{available}</b></span></div></Card>
const Metric=({label,value,onClick}:{label:string;value:number;onClick?:()=>void})=>onClick?<button type="button" className="card metric dashboard-link" onClick={onClick}><span>{label}</span><strong>{value}</strong></button>:<Card className="metric"><span>{label}</span><strong>{value}</strong></Card>

function Orders({state,query,setQuery,onOpen,onNew,onDelete}:{state:AppState;query:string;setQuery:(v:string)=>void;onOpen:(id:string)=>void;onNew:()=>void;onDelete?:(id:string)=>void}){const list=state.orders.filter(o=>activeStatuses.has(o.status)&&(o.client+' '+o.city+' '+o.number).toLowerCase().includes(query.toLowerCase()));return <><PageHeader title="Активни нарачки" action={<button className="primary" onClick={onNew}><CirclePlus size={18}/> Нова нарачка</button>}/><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Пребарај клиент, град или број..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><Card>{list.length===0?<Empty text="Нема активни нарачки."/>:<div className="orders-list">{list.map(o=><article key={o.id} onClick={()=>onOpen(o.id)}><div className="order-main"><div className="order-number">{o.number}</div><h3>{o.client}</h3><p>{o.city} • {o.date}</p></div><div className="order-qty"><span>0.25 L <b>{o.qty025+o.free025} пак.</b>{(o.qty025Pieces||0)+(o.free025Pieces||0)>0&&` + ${(o.qty025Pieces||0)+(o.free025Pieces||0)} пар.`}</span><span>BIB <b>{o.qty15} пак.</b>{(o.qty15Pieces||0)>0&&` + ${o.qty15Pieces} пар.`}</span><span>Флаери <b>{o.flyers} пар.</b></span></div><div className="order-actions"><span className={statusClass(o.status)}>{o.status}</span>{onDelete&&<button className="icon-btn danger" aria-label={`Избриши ${o.number}`} onClick={e=>{e.stopPropagation();onDelete(o.id)}}><Trash2 size={17}/></button>}<ChevronRight size={20}/></div></article>)}</div>}</Card></>}

function Packing({order,orders,onSelect,patchPacked,changeStatus,printOrder}:{order:Order|null;orders:Order[];onSelect:(id:string)=>void;patchPacked:(o:Order,key:keyof Order['packed'],value:boolean)=>void;changeStatus:(o:Order,s:OrderStatus)=>void;printOrder:(o:Order)=>void}){if(!order)return <><PageHeader title="Пакување"/><Empty text="Нема нарачки за пакување."/></>;const total025Packages=order.qty025+order.free025,total025Pieces=(order.qty025Pieces||0)+(order.free025Pieces||0),active=orders.filter(o=>activeStatuses.has(o.status)),packed=orders.filter(o=>deductStatuses.has(o.status));const orderButton=(o:Order)=><button className={o.id===order.id?'selected':''} onClick={()=>onSelect(o.id)} key={o.id}><div><b>{o.client}</b><small>{o.number}</small></div><span className={statusClass(o.status)}>{o.status}</span></button>;return <><PageHeader title="Пакување" action={<button className="ghost" onClick={()=>printOrder(order)}><Printer size={18}/> Печати пакинг листа</button>}/><div className="packing-layout"><Card className="order-selector"><h3>Нарачки</h3>{active.length>0&&<><div className="order-group-label">За пакување</div>{active.map(orderButton)}</>}{packed.length>0&&<><div className="order-group-label">Спакувани / излез</div>{packed.map(orderButton)}</>}</Card><div className="packing-main"><Card className="packing-summary"><div><span>{order.number}</span><h2>{order.client}</h2><p>{order.city} • {order.date}</p></div><select value={order.status} onChange={e=>changeStatus(order,e.target.value as OrderStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Card><div className="pack-rows"><PackRow checked={order.packed.regular025} disabled={order.stockDeducted} onChange={v=>patchPacked(order,'regular025',v)} title="0.25 L" qty={order.qty025} detail={breakdown(order.qty025,order.qty025Pieces||0)}/><PackRow checked={order.packed.bib15} disabled={order.stockDeducted} onChange={v=>patchPacked(order,'bib15',v)} title="1.5 L BIB" qty={order.qty15} detail={breakdown(order.qty15,order.qty15Pieces||0)}/><PackRow checked={order.packed.free025} disabled={order.stockDeducted} onChange={v=>patchPacked(order,'free025',v)} title="Гратис 0.25 L" qty={order.free025} detail={`${breakdown(order.free025,order.free025Pieces||0)} • одделно`}/><PackRow checked={order.packed.flyers} disabled={order.stockDeducted} onChange={v=>patchPacked(order,'flyers',v)} title="Флаери" qty={order.flyers} detail={`${order.flyers} парчиња`}/></div><Card className="take-card"><div><WarehouseIcon/><span>Вкупно за земање од магацин</span></div><h3>{total025Packages} пакети{total025Pieces>0?` + ${total025Pieces} парчиња`:''} 0.25 L</h3><p>редовни {order.qty025} пак. + гратис {order.free025} пак.{total025Pieces>0?` • дополнителни ${total025Pieces} пар.`:''}</p></Card></div></div></>}
const PackRow=({checked,disabled,onChange,title,qty,detail}:{checked:boolean;disabled:boolean;onChange:(v:boolean)=>void;title:string;qty:number;detail:string})=><label className={`pack-row ${checked?'done':''} ${disabled?'locked':''}`}><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><div className="check-ui">{checked&&<CheckCircle2/>}</div><div><h3>{title}</h3><p>{detail}</p></div><strong>{qty}</strong></label>

function WarehousePage({state,onEntry}:{state:AppState;onEntry:()=>void}){return <><PageHeader title="Магацин" action={<button className="primary" onClick={onEntry}><CirclePlus size={18}/> Ново движење</button>}/><div className="stock-grid"><StockCard title="0.25 L" packs={state.warehouse.p025.packages} pieces={state.warehouse.p025.pieces} total={state.warehouse.p025.total} reserved={reserved(state).p025} available={available(state).p025}/><StockCard title="1.5 L BIB" packs={state.warehouse.p15.packages} pieces={state.warehouse.p15.pieces} total={state.warehouse.p15.total} reserved={reserved(state).p15} available={available(state).p15}/><StockCard title="Флаери" packs={0} pieces={state.warehouse.flyers} total={state.warehouse.flyers} reserved={reserved(state).flyers} available={available(state).flyers}/></div><Card><div className="section-title"><div><h3>Последни движења</h3><p>Влезови, излези и корекции</p></div></div><MovementTable movements={state.movements.slice(0,8)}/></Card></>}
function ClientsPage({state}:{state:AppState}){return <><PageHeader title="Клиенти"/><div className="client-grid">{state.clients.map(c=>{const orders=state.orders.filter(o=>o.client===c.name);return <Card key={c.id} className="client-card"><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><h3>{c.name}</h3><p>{c.city}</p><div><span>Нарачки <b>{orders.length}</b></span><span>Последна <b>{orders[0]?.date||'—'}</b></span></div><small>{c.phone||'Нема внесен телефон'} • {c.contactPerson||'Нема контакт лице'}</small></Card>})}</div></>}
function MovementsPage({state}:{state:AppState}){return <><PageHeader title="Историја на залиха"/><Card><MovementTable movements={state.movements}/></Card></>}
const MovementTable=({movements}:{movements:AppState['movements']})=>movements.length===0?<Empty text="Сè уште нема движења на залиха."/>:<div className="table-wrap"><table><thead><tr><th>Датум</th><th>Производ</th><th>Тип</th><th>Пакети</th><th>Парчиња</th><th>Клиент / добавувач</th><th>Нарачка</th><th>Забелешка</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{m.date}</td><td>{productName(m.product)}</td><td><span className="status">{m.type}</span></td><td>{m.packages}</td><td>{m.pieces}</td><td>{m.party||'—'}</td><td>{m.orderNumber||'—'}</td><td>{m.note||'—'}</td></tr>)}</tbody></table></div>
function PrintingPage({state,printOrder}:{state:AppState;printOrder:(o:Order)=>void}){const active=state.orders.filter(o=>activeStatuses.has(o.status));const printGroup=()=>{const html=`<html><head><title>MAGACIN PRO</title><style>body{font-family:Arial;padding:24px}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #aaa;padding:8px;text-align:left}</style></head><body><h1>MAGACIN PRO</h1><h2>Активни нарачки</h2><table><tr><th>Број</th><th>Клиент</th><th>Град</th><th>0.25 L</th><th>BIB</th><th>Гратис</th><th>Флаери</th><th>Статус</th></tr>${active.map(o=>`<tr><td>${o.number}</td><td>${o.client}</td><td>${o.city}</td><td>${breakdown(o.qty025,o.qty025Pieces||0)}</td><td>${breakdown(o.qty15,o.qty15Pieces||0)}</td><td>${breakdown(o.free025,o.free025Pieces||0)}</td><td>${o.flyers} пар.</td><td>${o.status}</td></tr>`).join('')}</table><script>window.print()</script></body></html>`;const w=window.open('','_blank');w?.document.write(html);w?.document.close()};return <><PageHeader title="Печатење" action={<button className="primary" onClick={printGroup}><Printer size={18}/> Печати активни нарачки</button>}/><Card><div className="orders-list">{state.orders.map(o=><article key={o.id}><div className="order-main"><div className="order-number">{o.number}</div><h3>{o.client}</h3><p>{o.city} • {o.date}</p></div><button className="ghost" onClick={()=>printOrder(o)}><Printer size={17}/> Печати нарачка</button></article>)}</div></Card></>}
function SettingsPage({onReset,syncStatus,syncError,email,role,isAdmin,openAdmin}:{onReset?:()=>void;syncStatus:SyncStatus;syncError:string;email:string;role:'admin'|'operator';isAdmin:boolean;openAdmin:()=>void}){const labels:Record<SyncStatus,string>={loading:'Се вчитува...',offline:'Не е поврзано',syncing:'Се зачувува...',synced:'Синхронизирано',error:'Грешка во синхронизација'};return <><PageHeader title="Поставки"/><Card className="settings-card">{syncStatus==='error'?<CloudOff/>:<Cloud/>}<div><h3>Онлајн синхронизација</h3><p><b>{labels[syncStatus]}</b> • {email}{syncError&&<><br/><small>{syncError}</small></>}</p></div><button className="ghost" onClick={()=>void supabase.auth.signOut()}><LogOut size={18}/> Одјави се</button></Card><Card className="settings-card"><ShieldCheck/><div><h3>Кориснички профил</h3><p>Улога: <b>{role==='admin'?'Администратор':'Оператор'}</b>{isAdmin?' • Имаш целосни права.':' • Работиш во заедничкиот магацин.'}</p></div>{isAdmin&&<button className="ghost" onClick={openAdmin}>Отвори администрација</button>}</Card>{onReset&&<Card className="settings-card"><ArchiveRestore/><div><h3>Демо податоци</h3><p>Врати ја почетната залиха, клиентите и осумте демо нарачки.</p></div><button className="danger-btn" onClick={onReset}><RotateCcw size={18}/> Ресетирај демо податоци</button></Card>}<Card className="settings-card"><Truck/><div><h3>Автоматско ажурирање</h3><p>Апликацијата сама ја презема најновата верзија на истиот линк. Тековна верзија: <b>{appVersion}</b></p></div></Card></>}

function NewOrder({state,onClose,onSave}:{state:AppState;onClose:()=>void;onSave:(o:Order)=>void}){const [f,setF]=useState({client:'',city:'',p025:'0',e025:'0',p15:'0',e15:'0',free:'0',freePieces:'0',flyers:'0',note:''});return <Modal title="Нова нарачка" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({id:crypto.randomUUID(),number:makeOrderNumber(state.orders),client:f.client,city:f.city,date:new Date().toISOString().slice(0,10),qty025:+f.p025,qty025Pieces:+f.e025,qty15:+f.p15,qty15Pieces:+f.e15,free025:+f.free,free025Pieces:+f.freePieces,flyers:+f.flyers,note:f.note,status:'Нова',packed:{regular025:false,bib15:false,free025:false,flyers:false},stockDeducted:false})}} className="form-grid"><Field label="Пакети 0.25 L"><input min="0" type="number" value={f.p025} onChange={e=>setF({...f,p025:e.target.value})}/></Field><Field label="Дополнителни парчиња 0.25 L"><input min="0" max="14" type="number" value={f.e025} onChange={e=>setF({...f,e025:e.target.value})}/></Field><Field label="Пакети 1.5 L BIB"><input min="0" type="number" value={f.p15} onChange={e=>setF({...f,p15:e.target.value})}/></Field><Field label="Дополнителни парчиња BIB"><input min="0" max="5" type="number" value={f.e15} onChange={e=>setF({...f,e15:e.target.value})}/></Field><Field label="Гратис пакети 0.25 L"><input min="0" type="number" value={f.free} onChange={e=>setF({...f,free:e.target.value})}/></Field><Field label="Гратис дополнителни парчиња"><input min="0" max="14" type="number" value={f.freePieces} onChange={e=>setF({...f,freePieces:e.target.value})}/></Field><Field label="Флаери (парчиња)"><input min="0" type="number" value={f.flyers} onChange={e=>setF({...f,flyers:e.target.value})}/></Field><div className="calc-banner">0.25 L: <b>{f.p025}</b> пак. + <b>{f.e025}</b> пар. • BIB: <b>{f.p15}</b> пак. + <b>{f.e15}</b> пар. • Гратис: <b>{f.free}</b> пак. + <b>{f.freePieces}</b> пар.</div><Field label="Клиент"><input required value={f.client} onChange={e=>setF({...f,client:e.target.value})}/></Field><Field label="Град"><input required value={f.city} onChange={e=>setF({...f,city:e.target.value})}/></Field><Field label="Забелешка"><textarea value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></Field><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Откажи</button><button className="primary">Зачувај нарачка</button></div></form></Modal>}
function StockEntry({onClose,onSave}:{onClose:()=>void;onSave:(p:ProductKey,t:MovementType,pack:number,pieces:number,party:string,note:string,date:string)=>void}){const [f,setF]=useState({product:'p025' as ProductKey,type:'Влез' as MovementType,packages:'0',pieces:'0',party:'',note:'',doc:'',date:new Date().toISOString().slice(0,10)});return <Modal title="Ново движење на залиха" onClose={onClose}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave(f.product,f.type,+f.packages,+f.pieces,f.party,`${f.doc?`Документ: ${f.doc}. `:''}${f.note}`,f.date)}}><Field label="Производ"><select value={f.product} onChange={e=>setF({...f,product:e.target.value as ProductKey})}><option value="p025">0.25 L</option><option value="p15">1.5 L BIB</option><option value="flyers">Флаери</option></select></Field><Field label="Тип"><select value={f.type} onChange={e=>setF({...f,type:e.target.value as MovementType})}>{['Влез','Излез','Корекција','Враќање','Оштетување'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Пакети"><input type="number" min="0" value={f.packages} disabled={f.product==='flyers'} onChange={e=>setF({...f,packages:e.target.value})}/></Field><Field label="Индивидуални парчиња"><input type="number" min="0" value={f.pieces} onChange={e=>setF({...f,pieces:e.target.value})}/></Field><Field label="Добавувач / клиент"><input value={f.party} onChange={e=>setF({...f,party:e.target.value})}/></Field><Field label="Документ / фактура"><input value={f.doc} onChange={e=>setF({...f,doc:e.target.value})}/></Field><Field label="Датум"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Забелешка"><textarea value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></Field><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Откажи</button><button className="primary">Зачувај движење</button></div></form></Modal>}
function PackingPrint({o}:{o:Order}){
 const format=(value:number)=>String(value).replace(/\B(?=(\d{3})+(?!\d))/g,'.')
 const packageQuantity=(packages:number,pieces:number)=>`${packages} пакети${pieces?` + ${pieces} парчиња`:''}`
 const regular025Pieces=o.qty025*15+(o.qty025Pieces||0)
 const bib15Pieces=o.qty15*6+(o.qty15Pieces||0)
 const free025Pieces=o.free025*15+(o.free025Pieces||0)
 const packingResult=(packages:number,extraPieces:number,perPackage:number,total:number,unit:string)=>`${packages} × ${perPackage}${extraPieces?` + ${extraPieces}`:''} = ${format(total)} ${unit}`
 return <div className="print-sheet">
  <header className="packing-print-head"><span>MAGACIN PRO</span><h1>ПАКИНГ ЛИСТА</h1></header>
  <section className="packing-print-meta"><div><span>Број на пакинг листа</span><strong>{o.number}</strong></div><div className="packing-client"><span>Клиент</span><strong>{o.client}</strong></div><div><span>Датум</span><b>{o.date}</b></div><div><span>Град</span><b>{o.city}</b></div></section>
  <table className="packing-print-table"><thead><tr><th>Производ</th><th>Количина</th><th>Бр. во пакет</th><th>Пакување</th></tr></thead><tbody>
   <tr><td><strong>0.25 L</strong></td><td>{packageQuantity(o.qty025,o.qty025Pieces||0)}</td><td>15 шишиња</td><td><strong>{packingResult(o.qty025,o.qty025Pieces||0,15,regular025Pieces,'шишиња')}</strong></td></tr>
   <tr><td><strong>1.5 L BIB</strong></td><td>{packageQuantity(o.qty15,o.qty15Pieces||0)}</td><td>6 BIB</td><td><strong>{packingResult(o.qty15,o.qty15Pieces||0,6,bib15Pieces,'BIB')}</strong></td></tr>
   <tr><td><strong>Гратис 0.25 L</strong><small>Се пакува одделно</small></td><td>{packageQuantity(o.free025,o.free025Pieces||0)}</td><td>15 шишиња</td><td><strong>{packingResult(o.free025,o.free025Pieces||0,15,free025Pieces,'шишиња')}</strong><small>ОДДЕЛНО</small></td></tr>
   <tr><td><strong>Флаери</strong></td><td>{format(o.flyers)} парчиња</td><td>—</td><td><strong>{format(o.flyers)} парчиња</strong></td></tr>
  </tbody></table>
  <section className="packing-notes"><span>Забелешка</span><p>{o.note||'________________________________________________________________'}</p></section>
  <div className="packing-sign"><span>Спакувал</span><i/></div>
 </div>
}
export default App
